name: template-provision-test

on: 
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: kota65535/github-template-rename-action@v1.2.0
        with:
          from-name: test-gh-templates
          to-name: test-gh-templates-impl1
